// flow-typed signature: 01344d6f586527fa664d000249f2a92e
// flow-typed version: <<STUB>>/game_vfile:packages/game/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'game'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'game' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'game/config/webpack.config' {
  declare module.exports: any;
}

declare module 'game/dist/game' {
  declare module.exports: any;
}

declare module 'game/src/index' {
  declare module.exports: any;
}

declare module 'game/src/model/card-service' {
  declare module.exports: any;
}

declare module 'game/src/model/card-service.spec' {
  declare module.exports: any;
}

declare module 'game/src/model/card' {
  declare module.exports: any;
}

declare module 'game/src/model/card.spec' {
  declare module.exports: any;
}

declare module 'game/src/model/computer-player' {
  declare module.exports: any;
}

declare module 'game/src/model/computer-player.spec' {
  declare module.exports: any;
}

declare module 'game/src/model/game' {
  declare module.exports: any;
}

declare module 'game/src/model/game.spec' {
  declare module.exports: any;
}

declare module 'game/src/model/player' {
  declare module.exports: any;
}

declare module 'game/src/model/player.spec' {
  declare module.exports: any;
}

declare module 'game/test/support/test-cards' {
  declare module.exports: any;
}

declare module 'game/test/support/test-players' {
  declare module.exports: any;
}

// Filename aliases
declare module 'game/config/webpack.config.js' {
  declare module.exports: $Exports<'game/config/webpack.config'>;
}
declare module 'game/dist/game.js' {
  declare module.exports: $Exports<'game/dist/game'>;
}
declare module 'game/src/index.js' {
  declare module.exports: $Exports<'game/src/index'>;
}
declare module 'game/src/model/card-service.js' {
  declare module.exports: $Exports<'game/src/model/card-service'>;
}
declare module 'game/src/model/card-service.spec.js' {
  declare module.exports: $Exports<'game/src/model/card-service.spec'>;
}
declare module 'game/src/model/card.js' {
  declare module.exports: $Exports<'game/src/model/card'>;
}
declare module 'game/src/model/card.spec.js' {
  declare module.exports: $Exports<'game/src/model/card.spec'>;
}
declare module 'game/src/model/computer-player.js' {
  declare module.exports: $Exports<'game/src/model/computer-player'>;
}
declare module 'game/src/model/computer-player.spec.js' {
  declare module.exports: $Exports<'game/src/model/computer-player.spec'>;
}
declare module 'game/src/model/game.js' {
  declare module.exports: $Exports<'game/src/model/game'>;
}
declare module 'game/src/model/game.spec.js' {
  declare module.exports: $Exports<'game/src/model/game.spec'>;
}
declare module 'game/src/model/player.js' {
  declare module.exports: $Exports<'game/src/model/player'>;
}
declare module 'game/src/model/player.spec.js' {
  declare module.exports: $Exports<'game/src/model/player.spec'>;
}
declare module 'game/test/support/test-cards.js' {
  declare module.exports: $Exports<'game/test/support/test-cards'>;
}
declare module 'game/test/support/test-players.js' {
  declare module.exports: $Exports<'game/test/support/test-players'>;
}
